---
- name: Install Docker Ubuntu 
  gather_facts: yes
  hosts: all
  become: yes

  tasks:
    - name: Installing GPG Docker key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 7EA0A9C3F273FCD8
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Adding Docker repository for ARM
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes
      when: ansible_architecture  == "aarch64" or ansible_architecture == "arm64"

    - name: Adding Docker repository for x32/64
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes
      when: ansible_architecture  == "x86_64"

    - name: Updating apt cache
      apt:
        update_cache: yes

    - name: Installing Docker
      apt:
        name: docker-ce,docker-ce-cli,containerd.io,docker-compose
        state: latest

    - name: Starting Docker service
      service:
        name: docker
        state: started
        enabled: yes
...