---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install Python on debian based
    raw: '[[ -f "/etc/debian_version" ]]; apt-get install -y python'

  - name: Install Python on redhat based
    raw: '[[ -f "/etc/redhat_release" ]]; apt-get install -y python' 

  - name: Create .ssh folder 
    file:
      path: /root/.ssh 
      state: directory 

  - name: Create .ssh file 
    file: 
      path: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: '0600' 
      state: touch 

  - name: Add public key 
    lineinfile: 
      dest=/root/.ssh/authorized_keys
      line="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"  
      #  line: "{{lookup('file', '/root/.ssh/id_rsa.pub')}} 
