---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install Python on debian based
    raw: '[[ -f "/etc/debian_version" ]]; apt-get install -y python'

  - name: Install Python on redhat based
    raw: '[[ -f "/etc/redhat_release" ]]; yum install -y python' 
