---
- hosts: all
  gather_facts: no
  tasks:
  - name: Check Debian based OS 
    raw: test -e /etc/debian_version
    changed_when: false
    failed_when: false
    register: debian_based 
   
  - name: Check	RedHat based OS	
    raw: test -e /etc/redhat-release
    changed_when: false 
    failed_when: false 
    register: redhat_based

  - name: Install Python on debian based
    raw: 'apt-get update && apt-get install -y python'
    when: debian_based.rc == 0 

  - name: Install Python on redhat based
    raw: 'yum -y update && yum install -y python3'
    when: redhat_based.rc == 0

  - name: Test Python3 alternatie setup  
    raw: 'alternatives --list | grep python3' 
    register: python3_exists
    failed_when: "'unicornio' in python3_exists.stderr" 
    when: redhat_based.rc == 0
    
  - name:
    raw: 'update-alternatives --install /usr/bin/python python /usr/bin/python3 1'
    when: "'python3' not in python3_exists.stdout"
 
#     debug: var=python_exists.stdout_lines
#  - name: Set python3 as default on redhat based 
#    raw: 'update-alternatives --install /usr/bin/python python /usr/bin/python3 1'
##    raw: 'alternatives --install /usr/bin/python python /usr/bin/python3 1 && alternatives --set python /usr/bin/python3'
#    when: redhat_based.rc == 0  

