---
- name: Install Git utility 
  package: name=git state=latest 

- git:
    repo: "https://github.com/nik0chan/cluster-swarm" 
    dest: /srv/docker 

- name: Install NFS mount utility
  package:
    name: nfs-utils
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install NFS mount utility
  package:
    pkg: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Create NFS exports file 
  file: 
    path: /etc/exports
    owner: root
    group: root
    mode: '0600' 
    state: touch 

- name: Setup NFS share 
  lineinfile:
    dest: /etc/exports 
    line: "/srv/nfs	/srv/docker	{{NFS_NETWORK}}(rw,no_root_squash,no_subtree_check)"    

- name: Install Docker 
  shell: curl https://get.docker.com |sudo bash

- name: Start docker service 
  service: 
    name: docker
    state: started

# Do not create mountpoint using file, the mount module will create it
# automatically. This avoids problems where the module tries to change
# permissions on an existing directory

#- name: Mount NFS share
#  become: yes
#  mount:
#    fstype: nfs
#    name: "{{ item.path }}"
#    opts: "{{ item.opts | default(nfs_mount_opts) }}"
#    src: "{{ item.location }}"
#    dump: "{{ item.dump | default(omit) }}"
#    passno: "{{ item.passno | default(omit) }}"
#    state: mounted
#  with_items: "{{ nfs_share_mounts }}"
