---
- name: Check packages installed on system 
  package_facts: 
    manager: "auto"

- name: Install Git utility 
  package: name=git state=latest 
  when: "'git' not int ansible_facts.packages"
 
- name: Get cluster-swarm stuff from GitHub
  git:
    repo: "https://github.com/nik0chan/cluster-swarm" 
    dest: /srv/docker

- name: Install NFS mount utility
  package:
    name: nfs-utils
    state: latest
  when: 
    - ansible_os_family == "RedHat" 
    - "'nfs-utils' not int ansible_facts.packages"

- name: Install NFS mount utility
  package:
    pkg: nfs-kernel-server
    state: present
  when: 
    - ansible_os_family == "Debian"
    - "'nfs-kernel-server' not int ansible_facts.packages"

- name: Create NFS exports file 
  file: 
    path: /etc/exports
    owner: root
    group: root
    mode: '0600' 
    state: touch 

- name: Setup NFS share 
  lineinfile:
    dest: /etc/exports 
    line: "/srv/docker	{{NFS_NETWORK}}(rw,sync,no_subtree_check,sync)"    

- name: Start NFS Server [Debian based OS]
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian" 

- name: Start NFS Server [Redhat based OS]
  service: 
    name: nfs-server
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install Docker 
  shell: curl https://get.docker.com |sudo bash
  when: "'docker' not int ansible_facts.packages"

- name: Start docker service 
  service: 
    name: docker
    state: started

- name: Create Docker swarm
  shell: "echo '#!/bin/sh' > /srv/docker/join_swarm.sh | docker swarm init | grep '\\-\\-token'>> /srv/docker/join_swarm.sh"

- name: Create Docker swarm (2)
  file:
    path: /srv/docker/join_swarm.sh
    owner: root
    group: root
    mode: '0755'
    state: touch 
    
- name: Create Portainer data path 
  file: 
    path: /srv/docker/portainer/data
    state: directory

- name: Launch Services 
  shell: "/srv/docker/deploy-services.sh" 
