---
- name: Install Git utility 
  package: name=git state=latest 

- name: Get cluster-swarm stuff from GitHub
  git:
    repo: "https://github.com/nik0chan/cluster-swarm" 
    dest: /srv/nfs 

- name: Install NFS mount utility
  package:
    name: nfs-utils
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install NFS mount utility
  package:
    pkg: nfs-common,nfs-kernel-server
    state: present
  when: ansible_os_family == "Debian"

- name: Create NFS exports file 
  file: 
    path: /etc/exports
    owner: root
    group: root
    mode: '0600' 
    state: touch 

- name: Setup NFS share 
  lineinfile:
    dest: /etc/exports 
    line: "/srv/nfs	{{NFS_NETWORK}}(rw,sync,no_subtree_check,sync)"    


- name: Start NFS Server 
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes

- name: Install Docker 
  shell: curl https://get.docker.com |sudo bash

- name: Start docker service 
  service: 
    name: docker
    state: started

- name: Create Docker swarm
  shell: "echo '#!/bin/sh' > /srv/nfs/join_swarm.sh | docker swarm init | grep '\\-\\-token'>> /srv/nfs/join_swarm.sh"

- name: Create Docker swarm (2)
  file:
    path: /srv/nfs/join_swarm.sh
    owner: root
    group: root
    mode: '0755'
    state: touch 
    
#- name: Replace public portainer address
#  lineinfile: 
#    dest: /srv/nfs/portainer/stack.yaml 
#    regexp: '^  - lineinfile:
#      dest: /tmp/test.txt
#      regexp: '^replaceme'
#      line: '{{hos
